### ISSUE TITLE
While I always got CORS Error while start docker compose?

### ISSUE THREAD

**Issue by mingjinc** [strongloop/loopback-example-facade#46]
Error: Can't read from server.  It may not have the appropriate access-control-origin settings.
facade_1          
 |     at module.exports.failure (/usr/src/facadeAPI/node_modules/loopback-connector-swagger/lib/swagger-connector.js:116:17)

**Comment by hoangtrongphuc** [comment]
I have same issue !! 

Connection fails: Error: Can't read from server.  It may not have the appropriate access-control-origin settings.
It will be retried for the next request.

**Comment by mitant** [comment]
@hoangtrongphuc @mingjinc Hello, I saw the same problem that you two did.  Please see the open PR and try the changes locally.  This is an old example repository so I don't know when it will get merged but at least you can get it working.
